import styles from './raritySection.module.scss';

export default function RaritySection() {
  return (
    <section className={styles.raritySection}>
      <div className={styles.rarityChart}>
        <h2 className={styles.heading2}>Rarity</h2>
        <p className={styles.paragraph}>
          Each NFT is algorithmically generated by combining 170+ unique traits
          with varying rarity across categories.
        </p>
        <div className={styles.divBlock}>
          <h3>Types</h3>
          <div className={styles.rarityRowBlue}>
            <div className={styles.rarityNumber}>9,999</div>
            <div>Total Robots</div>
          </div>
          <div className={styles.rarityRow}>
            <div className={styles.rarityNumber}>Common</div>
            <div>Robotos</div>
          </div>
          <div className={styles.rarityRowBlue}>
            <div className={styles.rarityNumber}>Less Common</div>
            <div>Helmetos</div>
          </div>
          <div className={styles.rarityRow}>
            <div className={styles.rarityNumber}>Rare</div>
            <div>Cyborgos</div>
          </div>
          <div className={styles.rarityRowBlue}>
            <div className={styles.rarityNumber}>Super Rare</div>
            <div>Computos</div>
          </div>
          <img className={styles.image} src="/img/rarity-heads.png" alt="/" />
        </div>
        <div>
          <h3>Variations</h3>
          <div className={styles.rarityRowBlue}>
            <div className={styles.rarityNumber}>38</div>
            <div>Head Tops</div>
          </div>
          <div className={styles.rarityRow}>
            <div className={styles.rarityNumber}>32</div>
            <div>Eyes</div>
          </div>
          <div className={styles.rarityRowBlue}>
            <div className={styles.rarityNumber}>18</div>
            <div>Helmets</div>
          </div>
          <div className={styles.rarityRow}>
            <div className={styles.rarityNumber}>16</div>
            <div>Mouth</div>
          </div>
          <div className={styles.rarityRowBlue}>
            <div className={styles.rarityNumber}>18</div>
            <div>Ears</div>
          </div>
          <div className={styles.rarityRow}>
            <div className={styles.rarityNumber}>12</div>
            <div>Arms</div>
          </div>
          <div className={styles.rarityRowBlue}>
            <div className={styles.rarityNumber}>10</div>
            <div>Chassis Colors</div>
          </div>
          <div className={styles.rarityRow}>
            <div className={styles.rarityNumber}>9</div>
            <div>Backpacks</div>
          </div>
          <div className={styles.rarityRowBlue}>
            <div className={styles.rarityNumber}>6</div>
            <div>Computo Heads</div>
          </div>
          <div className={styles.rarityRow}>
            <div className={styles.rarityNumber}>6</div>
            <div>Chest Screens</div>
          </div>
          <div className={styles.rarityRowBlue}>
            <div className={styles.rarityNumber}>5</div>
            <div>Bodies</div>
          </div>
          <div className={styles.rarityRow}>
            <div className={styles.rarityNumber}>4</div>
            <div>Head Types</div>
          </div>
          <div className={styles.rarityRowBlue}>
            <div className={styles.rarityNumber}>4</div>
            <div>Human Faces</div>
          </div>
        </div>
      </div>
    </section>
  );
}
